### ISSUE TITLE
Martial Arts and weapons.

### ISSUE THREAD

**Issue by adriangaro** [MrPrimate/ddb-importer#104]
Would it be possible while importing the items for a character which is a monk to change the weapons which in beyond are considered martial weapons to use the martial dice formula if the dice size is lower?

**Comment by MrPrimate** [comment]
It _should_ be doing this - can you give me a character sheet where it does not

**Comment by adriangaro** [comment]
Here is the link to the char sheet, maybe to note is that import is configured to use items from the item compendium, so maybe that is what causes this. However, if that is the case, would it be possible to update those items from the compendium to reflect this? I need to use the compendium since I have the items munched from ddb and then modified a bit to add some custom effects after.

[Char sheet](https://ddb.ac/characters/44234169/BNhpBe)

**Comment by MrPrimate** [comment]
I'd suggest instead of importing from the compendium, you make the changes to the item on the character sheet, then click the D&DBeyond logo on the item titlebar, then "Ignore this item when importing the character" - it will then keep that item.
![monk](https://user-images.githubusercontent.com/3985378/110368294-c23d6d80-8040-11eb-9c95-4e2de2b5c1cf.png)
