### ISSUE TITLE
Generate rollable tables for relevant items

### ISSUE THREAD

**Issue by Varriount** [MrPrimate/ddb-importer#166]
Certain items (such as the [Bag of Tricks](https://www.dndbeyond.com/magic-items/bag-of-tricks)) include HTML tables in their descriptions. These tables are usually meant to be consulted when using the item (or describe variations of the item).

Ideally, DDB Importer would:
  - Detect items that contain these HTML tables.
  - Convert the HTML tables to rollable tables.
  - Configure the item so that when it is used, its corresponding rollable table(s) would be invoked (via the Midi-QoL and/or Item Macro modules).

**Comment by MrPrimate** [comment]
The latest version will generate a roll table and link where it's possible. No macro setup yet

**Comment by MaxPat931** [comment]
@MrPrimate 
Just imported a character, and had 16 rolltables generated just from the background. Because there is a feature created for each proficiency gained from the background, and they all contain the full description of the background, which has 4/5 roll tables (Personality Trait, Ideal, Bond, Flaw, sometimes an additional table). Could you make it so only one feature is created for the background?

![image](https://user-images.githubusercontent.com/86370342/131946040-4919a519-c987-40cb-90a6-25edc2b61273.png)

**Comment by MrPrimate** [comment]
@MaxPat931 good shout! I'll fix this in the next release
