### ISSUE TITLE
Journal Entry Adventure Muncher Taking Way Too Long

### ISSUE THREAD

**Issue by TRUE-mOISTtOAST** [MrPrimate/ddb-importer#314]
I'm currently trying to import all content from dnd beyond including my compendiums using the adventure muncher tool. Before attempting to import any compendiums, I imported everything else: spells, monsters, items, etc. The adventure much seems to be taking too long to import the journal because I had test world made where I was able to import the same compendium I'm attempting to import now on this world relatively quickly. Though in the test world, I had not imported the other assets before hand. Does the adventure muncher check each asset in the compendium to see if its missing from vtt? Is there a way to bypass it if that's the case?
By importing all assets before importing the adventure, I believe I may have significantly increased the time complexity of the adventure muncher

![image](https://user-images.githubusercontent.com/125205464/231294933-0cc490b7-8063-49ac-ad07-744d2cae5bca.png)

**Comment by TRUE-mOISTtOAST** [comment]
I reloaded the page and it seems to work, guess it was just a hiccup

**Comment by MrPrimate** [comment]
Likely your chrome session became disconnected, which can sometimes happen after a long time or transferring a lot of data.


To answer your question though, pre populating the compendiums with data is a good idea, as it speeds up adventure munching because the muncher doesn't need to download and parse it.
