### ISSUE TITLE
Warlock of the Fiend Monster Fixes

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#333]
Warlock of the Fiend Core changes:
1.  On the ability Hellfire, the necrotic damage imports in the versatile field when it should be a second damage formula instead.  
2.  On the ability Hellfire, the saving throw imports flat when it should be derived from charisma
3.  On the ability Fiendish Rebuke, the saving throw imports flat when it should be derived from charisma

Warlock of the Fiend Midi/auto effects changes:
1.  Same as Core above
2.  Same as Core above
3.  Same as Core above
4. For Hellfire and Fiendish Rebuke, flag them as magical damage, magical effect, and half dam save(I never trust the parsing of descriptions specially when theres 2 damage formulas)
5.  I automated the Dark One's Own Luck in Tpsoney's discord will link it here for you to grab, but understand theres currently a bug in midiqol, it does not like apostrophe's in item names so my copy deletes the apostrophe.  he may fix this before you ever read this.  

Here is the link to Dark Ones Own Luck(without the apostrophe)(its tposney's discord)
https://discord.com/channels/915186263609454632/1112091379561152599/1112091379561152599

**Comment by MotoMoto1234** [comment]
Fiendish Rebuke also is missing its 3/3 long rest

**Comment by MrPrimate** [comment]
Fiendish Rebuke fixed in next release, Hellfire damage is fixed.

The saving throws on features is a separate issue. They aren't _technically_ linked to a spell casting modifier, much like how Hellfire and Fiendish rebuke are _technically_ not spell/magical effects. It's harder to determine what the save dc for these is based on (when parsing) so will leave this as a future project to add.

**Comment by MrPrimate** [comment]
Closing this, and tracking flat saving throws in #337
